const steps = [
  {
    id: 1,
    title: "친구 추가 버튼 누르기",
    instruction: "친구 추가 화면을 열어보세요.",
    focusAreas: [{ x: 8, y: 24, w: 84, h: 8 }],
    speak: "상단의 사람 버튼을 눌러보세요.",
  },
  {
    id: 2,
    title: "전화번호로 친구 찾기",
    instruction: "전화번호 탭을 눌러 전화번호로 찾기를 선택하세요.",
    focusAreas: [{ x: 10, y: 36, w: 80, h: 8 }],
    speak: "전화번호로 친구를 찾는 탭을 눌러보세요.",
  },
  {
    id: 3,
    title: "키보드 꺼내기",
    instruction: "키보드를 꺼내 친구의 이름 입력할 준비를 하세요.",
    focusAreas: [{ x: 6, y: 46, w: 88, h: 10, pill: true }],
    speak: "친구의 이름을 입력하기 위해 키보드를 꺼내보세요.",
  },
  {
    id: 4,
    title: "친구의 이름 입력하기",
    instruction: "친구의 이름을 입력해보세요.",
    focusAreas: [{ x: 6, y: 46, w: 88, h: 10, pill: true }],
    inputPlaceholder: "메시지를 입력하세요",
    allowEnglish: false,
    speak: "친구의 이름을 입력한 후 다음으로 넘어가보세요.",
  },
  {
    id: 5,
    title: "키보드 꺼내기",
    instruction: "키보드를 꺼내 전화번호를 입력할 준비를 하세요.",
    focusAreas: [{ x: 6, y: 46, w: 88, h: 10, pill: true }],
    speak: "전화번호를 입력하기 위해 키보드를 꺼내보세요.",
  },
  {
    id: 6,
    title: "전화번호 입력하기",
    instruction: "전화번호를 입력해보세요.",
    focusAreas: [{ x: 6, y: 46, w: 88, h: 10, pill: true }],
    inputPlaceholder: "메시지를 입력하세요",
    speak: "전화번호를 입력하세요.",
  },
  {
    id: 7,
    title: "완료 및 확인",
    instruction: "작업이 완료되었는지 최종 확인해보세요.",
    focusAreas: [{ x: 6, y: 46, w: 88, h: 10, pill: true }],
    speak: "모든 작업을 확인하셨다면 완료해보세요.",
    completionSpeak: "잘하셨어요 아래 완료 버튼을 눌러 다음으로 가보세요.",
  },
];
export default steps;
